name: Delete feature stand
on:
  pull_request:
    types: [ closed ]

jobs:
  delete:
    uses: ./.github/workflows/delete-stage.yaml
    secrets:
      SA_DEPLOYER_PRIVATE_KEY: ${{ secrets.SA_FEATURE_DEPLOYER_PRIVATE_KEY }}
    with:
      stage_name: pr-${{ github.event.number }}
      environment: feature
  notify-stand-deleted:
    uses: ./.github/workflows/pr-comment.yaml
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    with:
      comment_tag: stand-deleted
      comment_text: "Feature stand was deleted"
      pr_number: ${{ github.event.number }}
      repo_name: ${{ github.repository }}