pipeline {
    agent any
    environment {
        YC_ACCOUNT_KEY_FILE = credentials('ajetmbs3831or9bpsbnp')
        YC_FOLDER_ID = credentials('b1gbobia866m35q0ad9v')
        YC_SUBNET_ID = credentials('e2lim4qvuhjn0qko593a')

        PACKER_SH = '/opt/yandex-packer/packer build -color=false'
    }
    stages {
        stage('Core') {
            steps {
                sh label: 'my-defined-label', script: "'/opt/yandex-packer/packer build -color=false' ./jenkins-packer/packer/base.json"
            }
        }
        stage('Role-Based') {
            steps {
                parallel(
                    nginx: {
                        sh label: 'my-defined-label', script: "'/opt/yandex-packer/packer build -color=false' ./jenkins-packer/packer/nginx.json"
                    },
                    django: {
                        sh label: 'my-defined-label', script: "'/opt/yandex-packer/packer build -color=false' ./jenkins-packer/packer/django.json" 
                    }
                )
            }
        }
    }
}

