pipeline {
    agent any
    environment {
        YC_ACCOUNT_KEY_FILE = "/home/user/liuyuanzhi.json"
        YC_FOLDER_ID = "b1gbobia866m35q0ad9v"
        YC_SUBNET_ID = "e2lim4qvuhjn0qko593a"

        PACKER_SH = '/opt/yandex-packer/packer build -color=false' 
    }
    stages {
        stage('Core') {
            steps {
                sh label: 'my-defined-label', script: "${env.PACKER_SH} ./jenkins-packer/packer/base.json"
            }
        }
        stage('Role-Based') {
            steps {
                parallel(
                    nginx: {
                        sh label: 'my-defined-label', script: "${env.PACKER_SH} ./jenkins-packer/packer/nginx.json"
                    },
                    django: {
                        sh label: 'my-defined-label', script: "${env.PACKER_SH} ./jenkins-packer/packer/django.json" 
                    }
                )
            }
        }
    }
}
